name: OpenSrcAction
description: "Open Source Verify"
inputs:
  rel_branch:
    description: ""
    required: true
    default: "main"
outputs:
  status:
    description:
    value: "Success"
runs:
 using: "composite"
 steps:
 - id: iop
   shell: bash
   run: cp -R ${{github.action_path}}/openverify ./OntarioVerify
 - id: transform
   shell: bash 
   name: TRANSFORM
   run: |
      ./OpenVerify/openverify/transform.linux.sh && \
      ./OpenVerify/openverify/transform.linux.sh && \
      ./OpenVerify/openverify/transform.linux.sh && \
      rm -rf ./OpenVerify/openverify && \
      zip -r OntarioVerify.zip
 - id: list
   name: LIST
   shell: bash
   run: ls -al
 - id: push
   name: PUSH
   shell: bash
   run: | 
     git remote -v
