name: OpenSrcAction
description: "Open Source Verify"
inputs:
  rel_branch:
    description: ""
    required: true
    default: "main"
outputs:
  status:
    description:
    value: "Success"
runs:
 using: "composite"
 steps:
 - id: iop
   shell: bash
   run: echo ${{github.action_path}}
  
